server.port=8080
server.servlet.context-path=/karuta-backend
spring.jersey.application-path=/rest
telnyx.apiKey=${TELNYX_API_KEY}
telnyx.profile=${TELNYX_PROFILE}
telnyx.number=${TELNYX_NUMBER}
server.tomcat.use-relative-redirects=true
server.forward-headers-strategy=native
# Auto-create tables if not exists
spring.jpa.hibernate.ddl-auto=update