-- USER SQL
CREATE USER karuta IDENTIFIED BY karuta_password 
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- ROLES
GRANT "RESOURCE" TO karuta ;
GRANT "CONNECT" TO karuta ;
GRANT "OEM_ADVISOR" TO karuta WITH ADMIN OPTION;
ALTER USER karuta DEFAULT ROLE "RESOURCE","CONNECT","OEM_ADVISOR";

-- SYSTEM PRIVILEGES
GRANT CREATE TRIGGER TO karuta WITH ADMIN OPTION;
GRANT ADVISOR TO karuta WITH ADMIN OPTION;
GRANT CREATE TABLE TO karuta WITH ADMIN OPTION;
GRANT CREATE ANY TRIGGER TO karuta ;
GRANT CREATE SESSION TO karuta WITH ADMIN OPTION;
GRANT UNLIMITED TABLESPACE TO karuta WITH ADMIN OPTION;
