
name: Java CI with Maven

on:
  push:
    branches:
      - master
      - test
      - tomcat10
  pull_request:
    branches:
      - master
      - tomcat10

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set variables if test
      if: ${{ github.ref == 'ref/head/test' }}
      run: |
        echo "Setting variables for tomcat 9"
        echo "JDK=11" >> "$GITHUB_ENV"
        echo "TARGET=9" >> "$GITHUB_ENV"
    - name: Set variables if tomcat 9
      if: ${{ github.ref  == 'ref/head/master' }}
      run: |
        echo "Setting variables for tomcat 9"
        echo "JDK=11" >> "$GITHUB_ENV"
        echo "TARGET=9" >> "$GITHUB_ENV"
    - name: Set variables if tomcat 10
      if: ${{ github.ref == 'ref/head/tomcat10' }}
      run: |
        echo "Setting variables for tomcat 10"
        echo "JDK=17" >> "$GITHUB_ENV"
        echo "TARGET=10" >> "$GITHUB_ENV"

    - name: Set up JDK ${{ env.JDK }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JDK }}
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package -Ptomcat$TARGET --file pom.xml

    - name: Create Draft Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}-${{ env.TARGET }}
        release_name: Draft Release for ${{ github.ref_name }}-${{ env.TARGET }}
        body: |
          Draft release for branch  ${{ github.ref_name }}-${{ env.TARGET }}
          Commit: ${{ github.sha }}
        draft: true
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/karuta-backend.war
        asset_name: karuta-backend-${{ env.TARGET }}.war
        asset_content_type: application/java-archive

