
name: Java CI with Maven

on:
  push:
    branches:
      - master
      - devel
      - tomcat10
  pull_request:
    branches:
      - master
      - tomcat10

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set variables
      id: vars
      run: |
        if [[ ${{ github.ref }} == 'ref/head/master' ]]; then
          echo "TARGET=9" >> $GITHUB_OUTPUT
          echo "JDK=11" >> $GITHUB_OUTPUT
        elif [[ ${{ github.ref }} == 'ref/head/devel' ]]; then
          echo "TARGET=9" >> $GITHUB_OUTPUT
          echo "JDK=11" >> $GITHUB_OUTPUT
        elif [[ ${{ github.ref }} == 'ref/head/tomcat10' ]]; then
          echo "TARGET=10" >> $GITHUB_OUTPUT
          echo "JDK=17" >> $GITHUB_OUTPUT
        fi

    - name: Set env variables
      run: echo "${{ steps.vars.outputs.TARGET }} ${{ steps.vars.outputs.JDK }}"
      env:
        TARGET: ${{ steps.vars.outputs.TARGET }}
        JDK: ${{ steps.vars.outputs.JDK }}
    
    - name: Set up JDK ${JDK}
      uses: actions/setup-java@v4
      with:
        java-version: ${JDK}
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package -Ptomcat${TARGET} --file pom.xml

    - name: Create Draft Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}-${TARGET}
        release_name: Draft Release for ${{ github.ref_name }}-${TARGET}
        body: |
          Draft release for branch  ${{ github.ref_name }}-${TARGET}
          Commit: ${{ github.sha }}
        draft: true
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/karuta-backend.war
        asset_name: karuta-backend-${TARGET}.war
        asset_content_type: application/java-archive

